<?php
/**
 * KeywordSetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  LinkedEvents
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Linked Events information API
 *
 * Linked Events provides categorized data on events and places using JSON-LD format.  Events can be searched by date and location. Location can be exact address or larger area such as neighbourhood or borough  JSON-LD format is streamlined using include mechanism. API users can request that certain fields are included directly into the result, instead of being hyperlinks to objects.  Several fields are multilingual. These are implemented as object with each language variant as property. In this specification each multilingual field has (fi,sv,en) property triplet as example.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace LinkedEvents;

/**
 * KeywordSetTest Class Doc Comment
 *
 * @category    Class */
// * @description Keyword sets are used to group keywords together into classification groups. For example, one set of keywords might describe themes used by an event provider and another could be used to describe audience groups.
/**
 * @package     LinkedEvents
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KeywordSetTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "KeywordSet"
     */
    public function testKeywordSet()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "originId"
     */
    public function testPropertyOriginId()
    {

    }

    /**
     * Test attribute "createdTime"
     */
    public function testPropertyCreatedTime()
    {

    }

    /**
     * Test attribute "lastModifiedTime"
     */
    public function testPropertyLastModifiedTime()
    {

    }

    /**
     * Test attribute "dataSource"
     */
    public function testPropertyDataSource()
    {

    }

    /**
     * Test attribute "lastModifiedBy"
     */
    public function testPropertyLastModifiedBy()
    {

    }

    /**
     * Test attribute "usage"
     */
    public function testPropertyUsage()
    {

    }

    /**
     * Test attribute "organization"
     */
    public function testPropertyOrganization()
    {

    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {

    }

}
